version: '3'

services:
  web:
    container_name: v-ticket-web
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production

  # 如果不需要 Cloudflare Tunnel，使用 host Nginx 代替，以下可以保留注释
  # tunnel:
  #   container_name: v-ticket-tunnel
  #   image: cloudflare/cloudflared:latest
  #   restart: unless-stopped
  #   command: tunnel --url http://web:3000
  #   depends_on:
  #     - web
