version: '3'

services:
  web:
    container_name: v-ticket-web
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DIRECT_URL=${DIRECT_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - MASTER_MNEMONIC=${MASTER_MNEMONIC}
      - WALLET_SECRET=${WALLET_SECRET}
      - BSC_RPC_URL=${BSC_RPC_URL}

  tunnel:
    container_name: v-ticket-tunnel
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --url http://web:3000
    depends_on:
      - web
